include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib_backup_20251113_1418/**

linter:
  rules:
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
    avoid_print: false